[package]
name = "sepia"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
clap = { version = "4.5.30", features = ["derive"] }
color-eyre = "0.6.3"
log = "0.4.25"
log4rs = "1.3.0"
xcap = "0.3.2"
